config/routes.rb
ImageSharingApp::Application.routes.draw do
  devise_for :users
  resources :albums

  resources :photos
  root :to => "albums#home"
  get "/my_profile", to: "albums#my_albums"

end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :photos
  belongs_to :user

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps
  field :tagline, type: String
  field :image, type: String

  validates_uniqueness_of :tagline
  validates_presence_of :tagline
  validate :tagline_must_be_valid

  mount_uploader :image, ImageUploader

  belongs_to :album

  def tagline_must_be_valid
    validate_name(:tagline)
  end

  def validate_name(field_name)
    if send(field_name.to_s) && !(send(field_name.to_s) =~ /^[a-zA-Z,. ]+$/)
      errors.add(field_name, "must be valid.")
    end
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home, :my_albums]

  def index
    @albums = Album.all
  end

  def show
    redirect_to root_path
  end

  def new
    @album = Album.new
  end

  def edit
  end

  def home
    @images = Photo.all.order(created_at: :desc).limit(25)
  end

  def my_albums
    @albums = current_user.albums
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        @album.user = current_user
        @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, photos_attributes: [:id, :tagline, :image])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album do |f| %>
  <%= f.input :name %>
  <h4>Photos</h4>
  <div id='photos'>
    <%= f.simple_fields_for :photos do |photo| %>
      <%= render 'photo_fields', :f => photo %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add photo', f, :photos %>
    </div>
  </div>
  <%= f.submit 'Save', :class => "btn btn-primary", :disabled =>"true" %>
<% end %>

<style type="text/css">
  .links{
    margin: 20px 0;
  }
</style>

app/views/albums/_photo_fields.html.erb
<div class='nested-fields'>
    <%= f.input :tagline %>
    <%= f.file_field :image %>
    <%= link_to_remove_association "remove photo", f %>
</div>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/home.html.erb
<div class="container">

  <h1 class="my-4 text-center text-lg-left">Gallery</h1>

  <div class="row">
    <% @images.each do |image| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <a href="#">
            <%= image_tag(image.image_url, :class => 'img-fluid img-thumbnail', :style => "width: 100%") %>
            <div class="caption">
              <p><b>Tag Line: <%=image.tagline%></b></p>
              <p><b>Album: <%=image.album.name%></b></p>
              <p><b>Created By: <%=image.album.user.email%></b></p>
            </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/my_albums.html.erb
<h2>My Albums</h2>
  <div class="panel-group" id="accordion">
    <%@albums.each do |album|%>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><%= album.name%></a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <% album.photos.each do |image| %>
            <div class="col-lg-3 col-md-4 col-xs-6">
              <a href="#" class="d-block mb-4 h-100">
                <%= image_tag(image.image_url, :class => 'img-fluid img-thumbnail', :style => "width: 100%") %>
              </a>
            </div>
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/albums/new.html.erb
<!-- Page Content -->
<div class="container">

  <h1 class="my-4 text-center text-lg-left">New album</h1>

	<%= render 'form' %>

<%= link_to 'Back', albums_path %>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageSharingApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %><!-- 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Image Sharing App</a>
    </div>
    <ul class="nav navbar-nav">
  	<% if user_signed_in? %>
      <li>
      	  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      </li>
  	<% else %>
    	<li><%= link_to "Sign up", new_user_registration_path %></li>
    	<li><%= link_to "sign in", new_user_session_path %></li>
	  <% end %>
	  <% if user_signed_in? %>
      <li><a href="/my_profile">My Profile</a></li>
      <li><a href="<%=new_album_path%>">Create New Album</a></li>
	  <% end %>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>